apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-orders
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/nishant-minj/microservices-repo.git
    targetRevision: HEAD
    path: k8s-manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
